### ISSUE TITLE
[5.0.2] Compile error after installation language ps-AF

### ISSUE THREAD

**Issue by fgsw** [joomla/core-translations#961] opened 2024-01-15 12:13 UTC
### Steps to reproduce the issue

1. Installation language ps-AF (Pashto Afghanistan).
2. activate content language ps-AF
3. set ps-AF as default administrator language.

### Expected result
Language work.

### Actual result
System Error Page: ``` Fatal error: Cannot declare class En_GBLocalise, because the name is already in use in /mnt/data/vhosts/casite-1461580.cloudaccess.net/httpdocs/administrator/language/ps-AF/localise.php on line 23```

![Screen Shot 2023-12-14 at 09 11 23](https://github.com/joomla/joomla-cms/assets/147295380/d3a18f85-28db-4840-b3c6-339a4f4b5177)

![Screen Shot 2023-12-14 at 09 13 39](https://github.com/joomla/joomla-cms/assets/147295380/d6f9dff5-fb3b-4158-a367-7859eb4ab432)

### System information (as much as possible)

![Untitled](https://github.com/joomla/joomla-cms/assets/147295380/3c7dd375-0cb2-483b-93ff-137e16ab67dd)

### Additional comments

Reported at https://github.com/joomla/joomla-cms/issues/42511.

**Comment by tecpromotion** [comment] 2024-01-15 12:17
This needs to be fixed in crowdin. I'll take a look.

**Comment by tecpromotion** [comment] 2024-01-15 12:29
fixed in crowdin and informed transaltor to build an new version for 5.0.2

**Closed by tecpromotion** 2024-01-15 12:29 UTC

**Comment by fgsw** [comment] 2024-01-15 14:30
Thanks @tecpromotion.

**Comment by icc365** [comment] 2024-01-30 23:13
Surprisingly, I have encountered a similar scenario building my template but in the Admin, changing my user to en-CA for both the backend and front-end, I get the same kind of error (including a 500 error, locking me out). That file in question also shows the `abstract class En_GBLocalise`

**Comment by tecpromotion** [comment] 2024-01-31 07:06
> Surprisingly, I have encountered a similar scenario building my template but in the Admin, changing my user to en-CA for both the backend and front-end, I get the same kind of error (including a 500 error, locking me out). That file in question also shows the `abstract class En_GBLocalise`

Same problem.

I have informed the responsible proofreader.

**Comment by particthistle** [comment] 2024-01-31 07:34
@tecpromotion - Issue is also in en-AU, en-NZ and en-US. Please update in Crowdin and let me know when I can package them up too. 
/language/xx-XX/localise.txt
/administrator/language/xx-XX/localise.txt

**Comment by tecpromotion** [comment] 2024-01-31 08:21
I have now customised all languages in Crowdin myself.

@particthistle you can start with your languages. Please also check whether the yoursites.site_check.ini file has been deleted. It was accidentally added to the core and I had deleted it globally recently, but I can still see it in your current package for en-CA in the administartor directory.

**Comment by particthistle** [comment] 2024-02-26 00:19
After an annoying stint with Crowdin last week, en-AU, en-CA, en-NZ and en-US are all checked, fixed and updated to 4.4.3.1 and 5.0.3.1.

The yoursites.site_check.ini file had been already out of a previous version of the language packs but is confirmed to not be in these packs moving forward.

_If you used en-CA  4.4.x.x language pack prior to 4.4.3 and think that the yoursites.sites_check.ini file installed on your site you can safely remove it (unless you're using the Yoursites Component) from /administrator/language/en-CA/_

**Comment by ghost** [comment] 2026-05-23 09:33
> fixed in crowdin and informed translator to build an new version for 5.0.2

@tecpromotion the issue is still the same as https://downloads.joomla.org/language-packs/translations-joomla5/downloads/joomla5-pashto-afghanistan/5-0-1-1 is the newest language-pack since the release at Tuesday, 05 December 2023.

Please reopen the issue.

**Comment by tecpromotion** [comment] 2026-05-23 09:49
The translator has been informed. That isn't maintained on GitHub; it needs to be updated in Crowdin and then re-uploaded by the translator.

**Comment by ghost** [comment] 2026-05-23 09:55
@tecpromotion Thanks for your update.
